[id="cnf-best-practices-vz-scc"]
= CNF Security Context Constraints (SCC)

Verizon plans to create four SCC profiles in the VCP WebScale platform. All Apps are expected to fit in Category 1 or Category 1-no-uid0 (a variation of category 1 for Aspen Mesh, see description below) employing the default SCC profile. Apps matching Category 2 or Category 3 below require exception approval from Verizon VCP HQ Planning team. Apps that require further exceptions in the SCC profile will need to organize an exception request with Verizon VCP HQ Planning team to explain their requirements and obtain a Verizon SEAT exception.

Applications *MUST* use one of the approved Security Context Constraints profiles unless an exception (SEAT) is approved by Verizon.

.VCP CNF requirement
[IMPORTANT]
====
Applications must use the Verizon defined SCCs otherwise exceptions are required
====

[id="cnf-best-practices-scc-permissions-for-an-application"]
== Setting SCC permissions for applications

Permissions to use an SCC is done by adding a cluster role that has _uses_ permissions for the SCC and then rolebindings for the users within a namespace to that role for users that need that SCC. Application admins can create their own role/rolebindings to assign permissions to a Service Account.

.Example
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: “restricted-scc-cat-1-role”
  labels:
    app: some-app
rules:
  - apiGroups:
  - security.openshift.io
resourceNames:
  - restricted-cat-1
resources:
  - securitycontextconstraints
verbs:
  - use
----

[id="cnf-best-practices-scc-application-categories"]
== SCC Application Categories

[id="cnf-best-practices-vz-cnfs-that-do-not-require-advanced-networking"]
=== CNFs that do not require advanced networking features (Category 1)

This is the default SCC for all users if your namespace does *not* use service mesh. This kind of CNFs shall

. Uses the default CNI (OVN) network interface.
. Not request `NET_ADMIN` or `NET_RAW` for advanced networking functions.

.SCC definition (default)
[source,yaml]
----
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: restricted-cat-1
users: []
groups: []
priority: null
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  - NET_RAW
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - ‘*’
supplementalGroups:
type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
----

[id="cnf-best-practices-vz-cnfs-that-require-service-mesh"]
== CNFs that require Service Mesh (Category 1 - no-uid0)

CNFs that utilize Service Mesh sidecars for mTLS and load balancing features must utilize an alternative to the restricted SCC Category 1 defined in section “SCC Application Categories” due to current Service Mesh limitation around requirements to use a specific UID (1337). An alternate SCC called restricted-no-uid0 has been provided in the platform and is available to all tenants without special requests necessary.

.CNFs that require Service Mesh (Category 1 - no-uid0)
[source,yaml]
----
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
name: restricted-no-uid0
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:authenticated
metadata:
annotations:
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - ‘*’
supplementalGroups:
  type: RunAsAny
users: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
----

[id="cnf-best-practices-vz-cnfs-that-require-advanced-features"]
== CNFs that require advanced networking features (Category 2)

The CNFs with following characteristics may fall into this category:

. Manipulate the low-level protocol flags, such as the 802.1p priority, VLAN tag, DSCP value, etc.
. Manipulate the interface IP addresses or the routing table or the firewall rules on-the-fly. 3. Process Ethernet packets

This kind of CNF may:

. Use Macvlan interface to sending and receiving Ethernet packets
. Request CAP_NET_RAW for creating raw sockets
. Request CAP_NET_ADMIN for
    .. Modify the interface IP address on-the-fly
    .. Manipulating the routing table on-the-fly
    .. Manipulating firewall rules on-the-fly
    .. Setting packet DSCP value

.Recommended SCC definition
[source,yaml]
----
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: cnf-catalog-2
users: []
groups: []
priority: null
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: [NET_ADMIN, NET_RAW]
defaultAddCapabilities: null
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - ‘*’
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projecte
----
