[id="cnf-best-practices-openshift-virtualization-and-cnv-best-practices"]
= OpenShift virtualization and CNV best practices

OpenShift Virtualization is generally-available for enterprise workloads, such throughput- and latency-insensitive workloads that may be added to the cluster. VNFs and other throughput or latency-sensitive applications can be considered only after careful validation.

OpenShift Virtualization should be installed according to its documentation, and only documented supported features may be used unless an explicit exception has been granted. See link:https://docs.openshift.com/container-platform/latest/virt/about-virt.html[About OpenShift Virtualization].

In order to improve overall virtualization performance and reduce CPU latency, critical VNFs can take advantage of OpenShift Virtualization's high-performance features. These can provide the VNFs with the following features:

* link:https://docs.openshift.com/container-platform/latest/virt/virtual_machines/advanced_vm_management/virt-dedicated-resources-vm.html[Dedicated resources for virtual machines]

* link:https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/#requesting-dedicated-cpu-for-qemu-emulator[Dedicated CPU for QEMU emulators]

* link:https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#iothreads-with-qemu-emulator-thread-and-dedicated-pinned-cpus[A separate physical CPU] so as to not affect the CPU latency for workloads.

[NOTE]
====
Similar to OpenStack, OpenShift Virtualization supports the link:https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#device-role-tagging[device role tagging mechanism] for the network interfaces (same format as it is in OSP). Users will be able to tag Network interfaces in the API and identify them in device metadata provided to the guest OS via the config drive.
====

