[id="cnf-best-practices-ipv4-ipv6"]
= IPv4 & IPv6

Dual stack will be supported in webscale 1.5 in production within the webscale environment.
Initial clusters for early testing are IPv4 with a NAT46/64 solution. See Section 16.3 for more
information. Note that private and registered IPv4 space is limited. IPv4 should only be used
when absolutely necessary.

Applications should discover services via DNS by doing an AAAA and A query. If an application gets a AAAA response the application should prefer using the IPv6 address in the AAAA response for application sockets.

Pods will receive a /128 and /32 for IPv6 and IPv4 respectively. IPv6 Services will be assigned a
/128 address from a separate network in just the same manner that IPv4 services are assigned a
/32 from a network specific to services.

The following example is output from inside an example pod.

[source,terminal]
----
bash-4.4$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state
UNKNOWN group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group
default qlen 1000
link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state
DOWN group default qlen 1000
link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
4: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state
DOWN group default qlen 1000
link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: eth0@if84: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8500 qdisc
noqueue state UP group default
link/ether 0a:58:c0:a8:02:3d brd ff:ff:ff:ff:ff:ff link-
netnsid 0
inet 192.168.2.61/23 brd 192.168.3.255 scope global eth0
valid_lft forever preferred_lft forever
inet6 fd35:0:0:3::3d/64 scope global
valid_lft forever preferred_lft forever
inet6 fe80::858:c0ff:fea8:23d/64 scope link
valid_lft forever preferred_lft forever
----

Pods will not need to do neighbor discovery or SLAAC, they will be assigned an address by
kubernetes.

Services should be created as IPv6 only services wherever possible. If an application requires dual
stack it should create a dual stack service. In OpenShift 4.12, you can declare ipFamilyPolicy:
PreferDualStack which will present an IPv4 and IPv6 address in the service.

The following example is output from a native Kubernetes service.

[source,terminal]
----
sh-4.2# oc get svc kubernetes -n default -o wide
NAME       TYPE      CLUSTER-IP EXTERNAL-IP PORT(S) AGE SELECTOR
kubernetes ClusterIP fd02::1    <none>      443/TCP 21h <none>
----

In OpenShift Container Platform 4.7+, you can declare `ipFamilyPolicy: PreferDualStack` which will present an IPv4 and IPv6 address in the service.

.VCP CNF recommendation
[IMPORTANT]
====
Webscale 1.5+ will be deployed with a dual stacked pod network, applications must support dual stacked pods and set service address family appropriately based on desired IP protocol of the application.
====

.CNF recommendation
[IMPORTANT]
====
IPv4 should only be used inside a pod when absolutely necessary.
====

.CNF recommendation
[IMPORTANT]
====
Services should be created as IPv6 only services wherever possible. If an application requires dual stack it should create a dual stack service.
====

For more information, see link:https://kubernetes.io/docs/concepts/services-networking/dual-stack[IPv4/IPv6 dual-stack].

To configure IPv4/IPv6 dual-stack, set dual-stack cluster network assignments:

[source,yaml]
----
kube-apiserver:
  --service-cluster-ip-range=<IPv4 CIDR>,<IPv6 CIDR>
----



