[id="cnf-best-practices-cnf-security"]
= Workload security

In OCP, it is possible to run privileged containers that have all of the root capabilities on a host machine, allowing the ability to access resources which are not accessible in ordinary containers. This, however, increases the security risk to the whole cluster. Containers should only request those privileges they need to run their legitimate functions. No containers will be allowed to run with full privileges without an exception.

The general guidelines are:

. Only ask for the necessary privileges and access control settings for your application.

. If the function required by your workload can be fulfilled by OCP components, your application should not be requesting escalated privilege to perform this function.

. Avoid using any host system resource if possible.

. Leveraging read only root filesystem when possible.

.Workload requirement
[IMPORTANT]
====
Only ask for the necessary privileges and access control settings for your application

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-security-context-non-root-user-check[access-control-security-context-non-root-user-check]
====

.Workload requirement
[IMPORTANT]
====
If the function required by your workload can be fulfilled by OCP components, your application should not be
requesting escalated privilege to perform this function.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-security-context-privilege-escalation[access-control-security-context-privilege-escalation]
====

.Workload requirement
[IMPORTANT]
====
Avoid using any host system resource.

See test cases link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-pod-host-ipc[access-control-pod-host-ipc], 
link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-pod-host-pid[access-control-pod-host-pid]
====

.Workload requirement
[IMPORTANT]
====
Do not mount host directories for device access.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-pod-host-path[access-control-pod-host-path]
====

.Workload requirement
[IMPORTANT]
====
Do not use host network namespace.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-namespace[access-control-namespace]
====

.Workload requirement
[IMPORTANT]
====
Workloads may not modify the platform in any way.

See test cases link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-base-image[platform-alteration-base-image], link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-sysctl-config[platform-alteration-sysctl-config]
====
