[id="cnf-best-practices-multus"]
= MULTUS

MULTUS is a meta-CNI that allows multiple CNIs that it delegates to. This allows pods to get additional interfaces beyond `eth0` via additional CNIs. Having additional CNIs for SR-IOV and MacVLAN interfaces allow for direct routing of traffic to a pod without using the pod network via additional interfaces. This capability is being delivered for use in only corner case scenarios, it is not to be used in general for all applications. Example use cases include bandwidth requirements that necessitate SR-IOV and protocols that are unable to be supported by the load balancer. The OVN based pod network should be used for every interface that can be supported from a technical standpoint.

.Workload requirement
[IMPORTANT]
====
Unless an application has a special traffic requirement that is not supported by SPK or ovn-kubernetes CNI
the applications must use the pod network for traffic
====

See link:https://docs.openshift.com/container-platform/latest/networking/multiple_networks/understanding-multiple-networks.html[Understanding multiple networks] for more information.

