[id="cnf-best-practices-cnf-operator-requirements"]
= CNF Operator requirements

.CNF requirement
[IMPORTANT]
====
Operators should be certified against the openshift version of the cluster they will be deployed on.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#affiliated-certification-operator-is-certified[affiliated-certification-operator-is-certified]
====

.CNF requirement
[IMPORTANT]
====
Operators must be compatible with our version of openshift

* See link:https://redhat-connect.gitbook.io/openshift-badges/badges/cloud-native-network-functions-cnf[Redhat Partner Guide for CNF Certification]

* See link:https://sdk.operatorframework.io/docs/best-practices/[Redhat Operator SDK & Best Practices], link:https://olm.operatorframework.io/docs/best-practices/[OLM Best Practices]

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-ocp-lifecycle[platform-alteration-ocp-lifecycle]
====

.CNF requirement
[IMPORTANT]
====
Operators must be in OLM bundle format (Operator Framework).

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#operator-install-source[operator-install-source]
====

.CNF requirement
[IMPORTANT]
====
Must be able to function without the use of openshift routes or ingress objects.
====

.CNF requirement
[IMPORTANT]
====
All custom resources for operators require podspecs for both pod image override as well pod quotas.
====

.CNF requirement
[IMPORTANT]
====
Operators must not use daemonsets

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-pod-owner-type[lifecycle-pod-owner-type]
====

.CNF requirement
[IMPORTANT]
====
The OLM operator CSV must support the "all namespaces" install method if the operator is upstream software. If the operator is a proprietary cnf operator it must support single namespaced installation. It is recommended for an operator to support all OLM install modes to ensure flexibility in our environment.
====

.CNF requirement
[IMPORTANT]
====
The operator must default to watch all namespaces if the target namespace is left NULL or empty string as this is how the OLM global-operators operator group functions.
====

.CNF requirement
[IMPORTANT]
====
All operator and operand images must be referenced using digest image tags "@sha256". Openshift "imagecontentsourcepolicy" objects (ICSP) only support mirror-by-digest at this time.
====

.CNF requirement
[IMPORTANT]
====
For general third party upstream operators (example: mongodb), the OLM package is recommended to be located within the Red Hat registries below to support our image mirror policy:

* `quay.io`

* `registry.redhat.io`

* `registry.connect.redhat.com`

* `registry.access.redhat.com`
====

.CNF requirement
[IMPORTANT]
====
Operators that are proprietary to a cnf application must ensure that their CRD's are unique, and will not conflict with other operators in the cluster.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#observability-crd-status[observability-crd-status]
====

.CNF requirement
[IMPORTANT]
====
If a cnf application requires a specific version of a third party non-proprietary operator for their app to function they will need to re-package the upstream third party operator and modify the APIs so that it will not conflict with the globally installed operator version.
====

.CNF requirement
[IMPORTANT]
====
Successful operator installation and runtime must be validated in pre-deployment lab environments before being allowed to be deployed to production.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#operator-install-status-succeeded[operator-install-status-succeeded]
====

.CNF requirement
[IMPORTANT]
====
All required RBAC must be included in the OLM operator bundle so that it's managed by OLM.
====

.CNF requirement
[IMPORTANT]
====
It is not recommended for a cnf application to share a proprietary operator with another cnf application if that application does not share the same version lifecycle. If a cnf application does share an operator the CRDs must be backwards compatible.
====
