[id="cnf-best-practices-pod-exit-status"]
= Pod exit status

The most basic requirement for the lifecycle management of pods in OpenShift is the ability to start and stop correctly. When starting up, health probes like liveness and readiness checks can be put into place to ensure the application is functioning properly.

There are different ways a pod can be stopped in Kubernetes. One way is that the pod can remain alive but non-functional. Another way is that the pod can crash and become non-functional. In the first case, if the administrator has implemented liveness and readiness checks, OpenShift can stop the pod and either restart it on the same node or a different node in the cluster. For the second case, when the application in the pod stops, it should exit with a code and write suitable log entries to help the administrator diagnose what the issue was that caused the problem.

Pods should use `terminationMessagePolicy: FallbackToLogsOnError` to summarize why they crashed and use stderr to report errors on crash

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#observability-termination-policy[observability-termination-policy]

.CNF requirement
[IMPORTANT]
====
All pods shall have a liveness, readiness and startup probes defined

See test cases link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-liveness-probe[lifecycle-liveness-probe], link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-readiness-probe[lifecycle-readiness-probe], link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-startup-probe[lifecycle-startup-probe]
====

OpenShift Container Platform and Kubernetes give application instances time to shut down before
removing them from load balancing rotations. However, applications must ensure they cleanly
terminate user connections as well before they exit.

On shutdown, OpenShift Container Platform sends a TERM signal to the processes in the container.
Application code, on receiving SIGTERM, stop accepting new connections. This ensures that load
balancers route traffic to other active instances. The application code then waits until all open
connections are closed, or gracefully terminate individual connections at the next opportunity, before exiting.

After the graceful termination period expires, a process that has not exited is sent the KILL signal,
which immediately ends the process. The `terminationGracePeriodSeconds` attribute of a pod or pod
template controls the graceful termination period (default 30 seconds) and can be customized per
application as necessary.
