[id="cnf-best-practices-far-edge-rt-requirements-and-cpu-engineering"]
= RT requirements and CPU engineering

In regards to CPU engineering and layout, the platform infrastructure Pods and operating system processes will require CPU resources in addition to workload requirements. To facilitate these requirements workload partitioning and performance profiles are used in tandem to accommodate this. The workload partitioning should be set up during the installation of the SNO cluster. An example cluster manifest is link:https://docs.openshift.com/container-platform/latest/scalability_and_performance/enabling-workload-partitioning.html[here].

Provided that these manifests are created at runtime, the `machineConfig` can be changed to modify the number of cores allocated to the house keeping pods and processes. Additionally, these partition manifests must correspond to the same configuration as the link:https://docs.openshift.com/container-platform/latest/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.html#ztp-sno-du-configuring-performance-addons_sno-configure-for-vdu[performance profile]..

This configuration can be verified by examining the allowed CPUs for systemd:

[source,terminal]
----
# cat /proc/1/status|grep Cpus_allowed_list
Cpus_allowed_list: 0-1,32-33
----

Housekeeping pods should have the following annotation in their namespace:

[source,yaml]
----
annotations:
  workload.openshift.io/allowed: management
----

This ensures they are given access to the same cores as above. More information can be found in the link:https://docs.openshift.com/container-platform/latest/scalability_and_performance/enabling-workload-partitioning.html[workload partitioning] documentation.

The platform provides the different types of CPU pools to the various application threads. The low-latency application, like vRAN, should be designed and implemented properly to fully utilize this platform. More information can be found in the link:https://docs.openshift.com/container-platform/4.13/scalability_and_performance/cnf-low-latency-tuning.html[Low latency tuning] documentation.

