[id="cnf-best-practices-far-edge-introduction"]
= Refactoring software as cloud-native network functions

Software down into the smallest set of microservices as possible.

It is hard to move a 1000LB boulder. However, it is easy when that boulder is broken down into many pieces. All containerized network functions (CNFs) should break apart each piece of the functions/services/processes into separate containers. These containers will still be within kubernetes pods and all of the functions that perform a single task should be within the same namespace.

There is a link:https://martinfowler.com/microservices/[quote] from Lewis and Fowler that describes this best:

[quote, Lewis and Fowler]
The microservice architectural style is an approach to developing a single application as a suite of small services, each running in its own process and communicating with lightweight mechanisms, often an HTTP resource API.These services are built around business capabilities and independently deployable by fully automated deployment machinery.

[id="cnf-best-practices-pods"]
== Pods

Pods are the smallest deployable units of computing that can be created and managed in Kubernetes.

A Pod can contain one or more running containers at a time. Containers running in the same Pod have access to several of the same Linux namespaces. For example, each application has access to the same network namespace, meaning that one running container can communicate with another running container over `127.0.0.1:<port>`. The same is true for storage volumes so all containers are in the same Pod have access to the same mount namespace and can mount the same volumes.
