[id="k8s-best-practices-cpu-isolation"]
[id="cpu-isolation"]
= CPU isolation

All the worker nodes in Webscale clusters have following performance profile applied to support Isolated CPUs with variations on the specific CPUs reserved or isolated based on the hardware.

[source,yaml]
----
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  annotations:
    kubeletconfig.experimental: |
      {"allowedUnsafeSysctls": ["net.*"], "systemReserved": {"memory": "16Gi", "cpu": "4", "ephemeral-storage": "1Gi"}}
  name: perf-profile-2m-worker
spec:
  cpu:
    isolated: 2-39,42-79
    reserved: 0-1,40-41
  hugepages:
    defaultHugepagesSize: 2M
    pages:
    - count: 24000
      node: 0
      size: 2M
    - count: 24000
      node: 1
      size: 2M
  nodeSelector:
    node-role.kubernetes.io/workerperf: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
  workloadHints:
    realTime: false
----

* `isolated` - Has the lowest latency. Processes in this group have no interruptions and so can, for example, reach much higher DPDK zero packet loss bandwidth.
* `reserved` - The housekeeping CPUs. Threads in the reserved group tend to be very busy, so latency-sensitive applications should be run in the isolated group


DPDK based application must use following annotations:

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: dpdk-pod
  annotations:
    cpu-quota.crio.io: "disable" # Mandatory for DPDK zero packet loss. Disables CPU CFS quota at pod run time
    irq-load-balancing.crio.io: "disable" # Mandatory for DPDK zero packet loss. Disables device interrupts on guaranteed CPUs
    cpu-load-balancing.crio.io: "disable" # Optional, depends on the CNF implementation
    cpu-c-states.crio.io: "disable" # Optional, depends on the CNF implementation
    cpu-freq-governor.crio.io: "performance" # Optional, depends on the CNF implementation
spec:
  runtimeClassName: performance-perf-profile-2m-worker #  If not provided, above annotations will be silently ignored, MUST match the name of the performance profile
----

Additionally, pods which require guaranteed resources must use CPU settings for Requests and Limits to an equal value which is an even number. This allows the pod to be scheduled on a full core within a hyperthreaded environment. Attempting to set an odd number of guaranteed cores (where requests are equal to limits) will result in the pod failing to start.

For a pod to be classified as Guaranteed the following conditions must exist:

* Every container in the Pod must have a memory limit and a memory request
* For every container in the Pod, the memory limit must equal the memory request
* Every container in the Pod must have a CPU limit and a CPU request
* For every container in the Pod, the CPU limit must equal the CPU request


