[id="k8s-best-practices-container-runtime"]
= Container runtime

OpenShift uses CRI-O as a CRI interface for Kubernetes. CRI-O manages `runC` for container image execution. CRI-O is an open-source container engine that provides a stable, performant platform for running OCI compatible runtimes. CRI-O is developed, tested and released in tandem with Kubernetes major and minor releases.


[NOTE]
====
Images should be OCI compliant. Red Hat recommends that you build images using Red Hat's open Universal Base Image (UBI).

See <<k8s-best-practices-ubi>> for additional information about UBI and support.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-isredhat-release[platform-alteration-isredhat-release]

**Impacts and Risks of Non-Compliance:** Non-Red Hat base images may lack security updates, enterprise support, and compliance certifications required for production use.
====

For more information about CRI-O, see the following:

* link:https://blog.openshift.com/add-a-layer-of-security-to-openshift-kubernetes-with-cri-o-in-read-only-mode/[Add a Layer of Security to OpenShift/Kubernetes with CRI-O in Read Only Mode]

* link:https://github.com/cri-o/cri-o/blob/master/docs/crio.8.md[CRI-O docs]

This environment is maintained with the following open source tools:

* link:https://github.com/opencontainers/runc[runc]
* link:https://github.com/containers/skopeo[skopeo]
* link:https://buildah.io/[buildah]
* link:https://podman.io/[podman]
* link:https://cri-o.io/[CRI-O]

