[id="k8s-best-practices-spk-integration-via-spk-operator"]
[id="spk-integration-via-spk-operator"]
= SPK Integration via SPK Operator

The SPK runs in a separate namespace from the workload. The workload will not have direct permissions to access this namespace. In order to allow applications to manage the lifecycle of the SPK deployment, the SPK operator is used. The SPK Operator defines several CRDs for which CRs are created in the CNF namespace:


[id="cnf-best-practices-spksnatpool"]
== SPKSnatpool
The SPKSnatpool is provisioned within the application namespace to configure source network address translations (SNAT) on egress network traffic for the SPK. When internal Pods connect to external resources, their internal cluster IP address is translated to one of the available IP addresses in the SNAT pool. Example:

[source,yaml]
----
apiVersion: k8s.f5net.com/v1
kind: F5SPKSnatpool
metadata:
  name: egress-snatpool
  namespace: spk-democnf
spec:
  addressList:
    - 10.183.247.229
    - fdb0:5b22:e86a:1122::22
    - 10.183.247.23
    - fdb0:5b22:e86a:1122::230
----

More details on the SPK operator are in the "SPK Operator User Guide".
