[id="k8s-best-practices-one-process-per-container"]
= One process per container

OpenShift organizes workloads into pods. Pods are the smallest unit of a workload that Kubernetes understands. Within pods, one can have one or more containers. Containers are essentially composed of the runtime that is required to launch and run a process.

Each container should run only one process. Different processes should always be split between containers, and where possible also separate into different pods. This can help in a number of ways, such as troubleshooting, upgrades and more efficient scaling.

However, OpenShift does support running multiple containers per pod. This can be useful if parts of the application need to share namespaces like networking and storage resources. Additionally, there are other models like launching init containers, sidecar containers, etc. which may justify running multiple containers in a single pod.

More information about pods can be found in link:https://docs.openshift.com/container-platform/latest/nodes/pods/nodes-pods-using.html[Using pods].

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-one-process-per-container[access-control-one-process-per-container]

