[id="k8s-best-practices-sr-iov-interface-settings"]
= SR-IOV interface settings

The following settings must be negotiated with the cluster administrator, for each network type available in the namespace:

* The type of netdevice to be used for the VF (kernel or userspace)

* The vlan ID to be applied to a given set of VFs available in a namespace

* For kernel-space devices, the IP allocation is provided directly by the cluster IP assignment mechanism.

* The option to configure the IP of a given SR-IOV interface at runtime, see link:https://docs.openshift.com/container-platform/4.12/networking/hardware_networks/add-pod.html[Adding a pod to an SR-IOV additional network].

[NOTE]
====
SR-IOV settings are enabled by the cluster administrator.
====

.Example SRIOVnetworknodepolicy
[source,yaml]
----
apiVersion: SRIOVnetwork.openshift.io/v1
kind: SRIOVNetworkNodePolicy
metadata:
  name: nnp-w1ens3f0grp2
  namespace: openshift-SRIOV-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  mtu: 9000
  nicSelector:
    deviceID: 158b
    pfNames:
    - ens3f0#50-63
    vendor: "8086"
  nodeSelector:
    kubernetes.io/hostname: worker-3
  numVfs: 64
  priority: 99
  resourceName: w1ens3f0grp2
----

The `SRIOVnetwork` CR creates the `network-attach-definition` within the target `networkNamespace`.

[id="example-1"]
.Example 1: Empty IPAM
[source,yaml]
----
apiVersion: SRIOVnetwork.openshift.io/v1
kind: SRIOVNetwork
metadata:
  name: SRIOVnet
  namespace: openshift-SRIOV-network-operator
spec:
  capabilities: '{ "mac": true }'
  ipam: '{}'
  networkNamespace: <WORKLOAD-NAMESPACE>
  resourceName: w1ens3f0grp2
  spoofChk: "off"
  trust: "on"
  vlan: 282
----

[id="example-2"]
.Example 2: Whereabouts IPAM
[source,yaml]
----
apiVersion: SRIOVnetwork.openshift.io/v1
kind: SRIOVNetwork
metadata:
  name: SRIOVnet
  namespace: openshift-SRIOV-network-operator
spec:
  capabilities: '{ "mac": true }'
  ipam: '{"type":"whereabouts","range":"FD97:0EF5:45A5:4000:00D0:0403:0000:0001/64","range_star t":"FD97:0EF5:45A5:4000:00D0:0403:0000:0001","range_end":"FD97:0EF5:45A5:4000:00D0:0403 :0000:0020","routes":[{"dst":"fd97:0ef5:45a5::/48","gw":"FD97:EF5:45A5:4000::1"}]}'
  networkNamespace: <WORKLOAD-NAMESPACE>
    resourceName: w1ens3f0grp2
    spoofChk: "off"
    trust: "on"
    vlan: 282
----

[id="example-3"]
.Example 3: Static IPAM
[source,yaml]
----
apiVersion: SRIOVnetwork.openshift.io/v1
kind: SRIOVNetwork
metadata:
  name: SRIOVnet
  namespace: openshift-SRIOV-network-operator
spec:
  capabilities: '{ "mac": true }'
  ipam: '{"type": "static","addresses":[{"address":"10.120.26.5/25","gateway":"10.120.26.1"}]}' networkNamespace: <WORKLOAD-NAMESPACE>
  resourceName: w1ens3f0grp2
  spoofChk: "off"
  trust: "on"
  vlan: 282
----

[id="example-4"]
.Example 4: Using Pod Annotations to attach
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations: k8s.v1.cni.cncf.io/networks: |-
    [
      {
        "name": "net1",
        "mac": "20:04:0f:f1:88:01",
        "ips": ["192.168.10.1/24", "2001::1/64"]
      }
    ]
----

The examples depict scenarios used within to deliver secondary network interfaces with and without IPAM to a pod.

<<example-1>> creates a network attachment definition that does not specify an IP address, <<example-2>> makes use of the static IPAM and <<example-3>> makes use of the whereabouts CNI that provides a cluster wide dhcp option.

The actual addresses used for both whereabouts and static IPAM are managed external to the cluster.

The above `SRIOVnetwork` CR will configure a network attachment definition within the workload namespace.

[source,terminal]
----
$ oc get net-attach-def -n <workload_namespace>
NAME       AGE
SRIOVnet   9d
----

Within the workload namespace the SR-IOV resource is consumed via a pod annotation:

[source,yaml]
----
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: SRIOVnet
----
