[id="k8s-best-practices-upgrade-expectations"]
= Upgrade expectations

* CNF vendors should expect that VCP Webscale Platform shall be upgraded to new versions on an ongoing basis employing CI/CD runtime deployment without any advance notice to CNF vendors.

* During VCP WebScale platform upgrades, the Kubernetes API deprecation policy defined in link:https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes Deprecation Policy] shall be followed

* CNFs are expected to maintain service continuity during Platform Upgrades, and during CNF version upgrades

* CNFs need to be prepared for nodes to reboot or shut down without notice.

* CNFs shall configure pod disruption budget appropriately to maintain service continuity during platform upgrades Applications should not be tied to a specific version of Kubernetes or any of its components

[IMPORTANT]
====
Applications MUST specify a pod disruption budget appropriately to maintain service continuity during platform upgrades. The budget should be defined with a balance such that it allows operational flexibility for the cluster to drain nodes, but restrictive enough so that the service is not degraded over upgrades. At least 10% of pods for any given app should be able to be evicted at any given time.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-pod-recreation[lifecycle-pod-recreation]
====

