[id="k8s-best-practices-application-dns-configuration-requirements"]
[id="application-dns-configuration-requirements"]
= Application DNS configuration requirements

Workloads should use the service name only as a configuration parameter for attaching to a service within your namespace, the cluster will append namespace name and kubernetes service nomenclature on behalf of the application via search string in DNS. This allows a generic name for a service that works in all clusters no matter what the namespace name is and what the cluster base FQDN is.

.Example
[source,terminal]
----
search clspcoykvzwcscp-y-xx-w1-001.svc.cluster.local
svc.cluster.local cluster.local kub2-4.csp-1.vzwops.com
nameserver 198.223.0.10
options ndots:5
----

If an application deploys a service in the namespace `clspcoykvzwcscp-y-xx-w1-001` and is attempting to access a service named `worker`, the application should just configure the client of the service with an FQDN of `worker`.

The DNS search suffix will append `clspcoykvzwcscp-y-xx-w1-001.svc.cluster.local` to the end of the name and result in a successful query for `worker.clspcoykvzwcscp-y-xx-w1-001.svc.cluster.local`. This allows an application to be less aware of the application's namespace name and genericize the configuration of the application.

[IMPORTANT]
====
Workloads must use the service name only as a configuration parameter for attaching to a service within your namespace
====

[IMPORTANT]
====
For FQDNs that are outside of their namespace (in another cluster or in the same cluster), applications must append a . at the end of the FQDN so as not to trigger search strings for the FQDN
====

.Example
[source,terminal]
----
nnrfe1-000.bbtpnj33.ne.nrf.5gc.vzims.com
clspcoykvzwcscp-y-xx-w1-001-scp-cache-headless.clspcoykvzwcscp-y-xx-w1-001.svc.cluster.local
----

For more information, see link:https://kubernetes.io/docs/concepts/services-networking/dns-pod-service[Kubernetes upstream reference for pod/service names and DNS].
