[id="k8s-best-practices-host-os"]
= Container host operating system

Red Hat Enterprise Linux CoreOS (RHCOS) is the next generation container operating system. RCHOS is part of OpenShift Container Platform and is used as the operating system for the control plane. it is the default operating system for worker nodes. RHCOS is based on RHEL, has some immutability, leverages the CRI-O runtime, contains container tools, and is updated through the Machine Config Operator (MCO).

The controlled immutability of RHCOS does not support installing RPMs or additional packages in the traditional way. Some 3rd party services or functionalities need to run as agents on nodes of the cluster.

For more information, see link:https://docs.openshift.com/container-platform/latest/architecture/architecture-rhcos.html[About RHCOS].

See test cases link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-ocp-node-os-lifecycle[platform-alteration-ocp-node-os-lifecycle], link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-boot-params[platform-alteration-boot-params]

**Impacts and Risks of Non-Compliance:** Incompatible node operating systems can cause stability issues, security vulnerabilities, and lack of vendor support.
