[id="k8s-best-practices-cnf-operator-requirements"]
= Workload Operator requirements

.Workload requirement
[IMPORTANT]
====
Operators should be certified against the openshift version of the cluster they will be deployed on.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#affiliated-certification-operator-is-certified[affiliated-certification-operator-is-certified]

**Impacts and Risks of Non-Compliance:** Uncertified operators may have security flaws, compatibility issues, and lack enterprise support, creating operational risks.
====

.Workload requirement
[IMPORTANT]
====
Operators must be compatible with our version of openshift

* See link:https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html/red_hat_software_certification_workflow_guide/assembly_working-with-operators_openshift-sw-cert-workflow-publishing-the-certified-container#con_certification-workflow-for-operators_openshift-sw-cert-workflow-working-with-operators[Redhat Operator Certification Workflow], link:https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-products-managed-by-an-operator_openshift-sw-cert-policy-container-images[Redhat Policy Guide for Operator Certification]

* See link:https://sdk.operatorframework.io/docs/best-practices/[OLM Best Practices], link:https://olm.operatorframework.io/docs/best-practices/[Operator SDK & Best Practices]

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#platform-alteration-ocp-lifecycle[platform-alteration-ocp-lifecycle]

**Impacts and Risks of Non-Compliance:** End-of-life OpenShift versions lack security updates and support, creating significant security and operational risks.
====

.Workload requirement
[IMPORTANT]
====
Operators must be in OLM bundle format (Operator Framework).

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#operator-install-source[operator-install-source]

**Impacts and Risks of Non-Compliance:** Non-OLM operators bypass lifecycle management and dependency resolution, creating operational complexity and update issues.
====

.Workload requirement
[IMPORTANT]
====
Must be able to function without the use of openshift routes or ingress objects.
====

.Workload requirement
[IMPORTANT]
====
All custom resources for operators require podspecs for both pod image override as well pod quotas.
====

.Workload requirement
[IMPORTANT]
====
Operators must not use daemonsets

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-pod-owner-type[lifecycle-pod-owner-type]

**Impacts and Risks of Non-Compliance:** Naked pods and DaemonSets lack proper lifecycle management, making updates, scaling, and recovery operations difficult or impossible.
====

.Workload requirement
[IMPORTANT]
====
The OLM operator CSV must support the “all namespaces” install method if the operator is upstream software "global operator".  If the operator is a proprietary cnf operator "vendor operator" it must support single namespaced installation.  It is recommended for an operator to  support all OLM install modes to ensure flexibility in our environment.
====

.Workload requirement
[IMPORTANT]
====
The operator must default to watch all namespaces if the target namespace is left NULL or empty string as this is how the OLM global-operators operator group functions.
====

.Workload requirement
[IMPORTANT]
====
Multiple versions of the same operator cannot exist on a single cluster.
====

.Workload requirement
[IMPORTANT]
====
All Operator and operand images must be referenced using digest image tags "@sha256". Openshift "imagecontentsourcepolicy" objects (ICSP) only support mirror-by-digest at this time.
====

[IMPORTANT]
====
For requesting Global operators (upstream 3rd party shared operators), the operators must come from one of the redhat provided operator catalogs
* `redhat-operator`
* `certified-operator`
* `community-operator`
====

.Workload requirement
[IMPORTANT]
====
Operators that are proprietary to a workload application must ensure that their CRD's are unique, and will not conflict with other operators in the cluster.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#observability-crd-status[observability-crd-status]

**Impacts and Risks of Non-Compliance:** Missing status subresources prevent proper monitoring and automation based on custom resource states.
====

.Workload requirement
[IMPORTANT]
====
If a workload application requires a specific version of a third party non-proprietary operator for their app to function they will need to re-package the upstream third party operator and modify the APIs so that it will not conflict with the globally installed operator version.
====

.Workload requirement
[IMPORTANT]
====
Successful operator installation and runtime must be validated in pre-deployment lab environments before being allowed to be deployed to production.

See test case link:https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#operator-install-status-succeeded[operator-install-status-succeeded]

**Impacts and Risks of Non-Compliance:** Failed operator installations can leave applications in incomplete states, causing functionality gaps and operational issues.
====

.Workload requirement
[IMPORTANT]
====
All required RBAC must be included in the OLM operator bundle so that it's managed by OLM.
====

.Workload requirement
[IMPORTANT]
====
It is not recommended for a workload application to share a proprietary operator with another workload application if that application does not share the same version lifecycle. If a workload application does share an operator the CRDs must be backwards compatible.
====

[IMPORTANT]
====
Applications providing OLM catalogs to bring their operators into a platform environment must ensure that their catalog has less than 1,000 images per application team, however applications should target a much lower number than this (preferably under 150-200 images)
====

.Workload requirement
[IMPORTANT]
====
Applications providing OLM catalogs to bring their operators into a platform environment must ensure that their catalog uses a FQDN name specific to their brand for their docker registry and provide a pull secret so that the images from their hosted registry can be accessed.
====

.Workload recommendation
[IMPORTANT]
====
It is recommended applications limit the scope of their OLM catalog to only operator packages needed for lifecycle upgrades, and the latest version installs following operator framework best practices by utilizing olm.skipRange to keep operator catalogs as small as possible.
====

.Workload requirement
[IMPORTANT]
====
When an operator subscription is created into a namespace, the operator's install plan must install all resources to that specific operator namespace. The only exception here are cluster scoped objects such as CRD's.
====

.Workload requirement
[IMPORTANT]
====
Operators must install to our environment using a subscription object only.  Pre-configuration or custom configuration using config maps should not be required to install your operator to our environment.
====

.Workload requirement
[IMPORTANT]
====
Operators are not permitted to use huge pages.
====

.Workload requirement
[IMPORTANT]
====
The size of operator catalog and all images required by operator catalog cannot exceed 200GB of storage for an application catalog.
====

.Workload requirement
[IMPORTANT]
====
Application vendors will need to increment their operator version to supply any hotfix or upgrade.  For example If your existing operator version is 1.6.9-0, and you need to supply a hotfix, then your new OLM package should be 1.6.9-1 and the new operator CSV should have a replace tag for the existing operator CSV.
====

.Workload requirement
[IMPORTANT]
====
Global operators are versioned to a release of the platform.  These versions only change when there is a new platform release.
====

.VCP CNF requirement
[IMPORTANT]
====
Operators are not permitted to be installed into a tenant app namespace. Operators that are installed with the  "Single Namespace" olm install mode must be installed into the tenants dedicated operator namespace.  Upstream 3rd party operators will be installed Globally with "All Namespaces" olm install mode into the openshift-operators namespace.
====
