// Metadata created by nebel
//
// ConvertedFromFile: cnf-reqs_1.3_single.adoc
// ConversionStatus: raw

[id="cnf-paas-core-edge"]
= PaaS Core/Edge

.Certificate Management

Certificate Management may be obtained through the platform via the network. A CSR may be generated to get a certificate signed via Citadel which should provide an ICA certificate. Platform certificate rotation on behalf of an application may happen.

.Distributed Tracing

Distributed L7 tracing may be supported by the platform via a Service Mesh with Jaeger as the UI to the trace data.

.Pod Security

SELinux is always enabled within OpenShift Container Platform and will be used to enforce syscalls that containers make. In addition, Kubernetes has another native function called pod security policies.

.Load Balancer/Service Proxy

[.mark]#OpenShift default load balancer, metalLB, can be used or any certified load balancer on Red Hat Openshift can be used, for instance F5 SPK or F5 BigIP. Applications must use the Load Balancer to get traffic into and out of the pod network#

.CI/CD Framework

Applications should target a CI/CD approach for deployment and validation.

.Kubernetes API versions

OpenShift platform supports the full Kubernetes APIs as well as additional API calls that are OpenShift specific. Documentation can be found at the below link:

https://docs.openshift.com/container-platform/4.7/rest_api/index.html[[.underline]#https://docs.openshift.com/container-platform/4.7/rest_api/index.html#]

