// Metadata created by nebel
//
// ConvertedFromFile: cnf-reqs_1.3_single.adoc
// ConversionStatus: raw

[id="cnf-security"]
= Security

.Elevated privilege container capabilities

Container images will not be granted use of any non-default Linux capabilities. Such images will be blocked from running entirely or will fail at runtime due to lack of privileges.

.CPI-810

All CNFs should be compliant with CPI-810. Work to determine CNFs compliance with CPI-810.

.Image Security

Images should be scanned by CVE scanners while stored in the Internal Registry. Vulnerabilities found during scanning will result in flags and deployment of images with vulnerabilities will require exceptions.

Images for use on the core solution must include digital signatures which validate that the image is from an authorized vendor, part or all of an authorized CNF delivered by the vendor, has a current component version, and has not been modified since signing. At a minimum the signature must include information identifying the container base image included as well as for the entire container contents. Accompanying software artifacts such as Helm charts, and shell scripts must be similarly signed individually.

.CNF network security

CNF Tenant security is the responsibility of the CNF team. Vendors must work through the onboarding process to create a security plan. CNFs must have the least permissions possible and CNFs must implement Network Policies that drop all traffic by default and permit only the relevant ports and protocols to the narrowest ranges of addresses possible.

.Secrets management

Secrets objects in OpenShift provide a way to hold sensitive information such as passwords, config files and credentials. There are 4 types of secrets; service account, basic auth, ssh auth and TLS. Secrets can be added via deployment configurations or consumed by pods directly. For more information on secrets and examples, see the following documentation.

https://docs.openshift.com/container-platform/4.7/nodes/pods/nodes-pods-secrets.html[[.underline]#https://docs.openshift.com/container-platform/4.7/nodes/pods/nodes-pods-secrets.html#]
