// Metadata created by nebel
//
// ConvertedFromFile: cnf-reqs_1.3_single.adoc
// ConversionStatus: raw

[id="cnf-app-def"]
= Application Deployment

One option for application deployment is via Helm v3. Helm provides a mechanism to deploy with site specific templates that allow for repeatable deployment in multiple locations.

Make use of values.yaml to make replicable deployments in different locations with different parameters.

It is recommended that Images be built with Red Hat's Universal Base Image.

.Standards

.Container Labeling Standards

Labels are used to organize and select subsets of objects. For example, labels enable a service to find and direct traffic to an appropriate pod. While pods can come and go, when labeled appropriately, the service will detect new pods, or a lack of pods, and forward or reduce the traffic accordingly.

When designing your label scheme, it may make sense to map applications as types, location, departments, roles, etc. The scheduler will then use these attributes when colocating pods or spreading the pods out amongst the cluster. It is also possible to search for resources by label.

.Image Standards

It is recommended that container images be built utilizing Red Hat's Universal Base Image as they will have a solid security baseline as well as support from Red Hat.

Vendors must satisfy 3 requirements related to maintaining proper workload isolation in a containerized environment:

* Work with Red Hat’s Restricted SCC¹
* Work with Red Hat’s Default SELinux Context¹
* Evidence the container image is secure:²

* Supported by dedicated, full time team providing releases of base image at least as quickly as:
** Scheduled release every 6 weeks to pick up less critical fixes.
** On-demand release for Critical or Important CVE within 5 days of CVE public release.
** Guarantees alignment with host OS packages, versions, etc. that will run tightly coupled to the container artifacts. Many CVEs and potential attacks result from mismatch of untested versions of utility functions.

* Ensures globally consistent time zone usage and resulting timestamps for global operators
* Enables Continuous Authorization to Operate (ATO). Authorize once, use many times.
* Meets requirements of DOD, for example Air Force/DISA STIG
* Supports system wide crypto consistency (e.g. must have same crypto implementation as our Red Hat host OS)
* Provides authentication of base layer via digital signature from originating vendor and strong signature authority

¹ This is meant to forbid all changes to both primary config files (SCC, SEL) and the many related files referenced by these primary files. All security configuration files must be unchanged from the vendor’s released version.

² The Red Hat UBI is able to meet these requirements and enables images built with it to meet these requirements.

If a vendor cannot satisfy these requirements, they will have to submit a Security Exception to Network Operations for approval. Security Planning will not support approval of this exception unless the vendor commits to a roadmap for satisfying all 3 of these requirements within 6 months.

Note this is not an exhaustive list of security requirements vendors must satisfy. For example, it does not cover general security requirements such as access control and logging.

.Universal Base Image information

https://developers.redhat.com/products/rhel/ubi/#assembly-field-sections-18455[[.underline]#https://developers.redhat.com/products/rhel/ubi/#assembly-field-sections-18455#]

UBI is designed to be a foundation for cloud-native and web applications use cases developed in containers. You can build a containerized application using UBI, push it to your choice of registry server, easily share it with others - and because it’s freely redistributable — even deploy it on non-Red Hat platforms. And since it’s built on Red Hat Enterprise Linux, UBI is a platform that is reliable, secure, and performant.

Base Images::

A set of base images (Micro, Minimal, Standard, and Multi-service) are provided to provide optimum starting points for a variety of use cases.

Runtime Languages::

A set of language runtime images (PHP, Perl, Python, Ruby, Node.js) enable developers to start coding out of the gate with the confidence that a Red Hat built container image provides.

Complementary packages::

A set of associated YUM repositories/channels include RPM packages and updates that allow users to add application dependencies and rebuild UBI container images anytime they want.

Red Hat UBI images are the preferred images to build CNFs on as they will leverage the fully supported Red Hat ecosystem. In addition, once a CNF is standardized on a Red Hat UBI, the image can be become Red Hat certified.

Red Hat UBI images are free to vendors so there is a low barrier of entry to getting started.

