name: Build and release PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Extract assets
        run: docker cp $(docker run --detach quay.io/redhat-docs/redhat-docs-pdf-template):/pdf-assets ./pdf-assets

      - name: Build PDF
        uses: docker://quay.io/redhat-docs/redhat-docs-pdf-template
        with:
          args: main.adoc

      - name: Create PDF release
        run: |
          echo $GITHUB_RUN_NUMBER > version.txt
          mv main.pdf k8s-best-practices-guide.pdf
          gh release create v2.0.$GITHUB_RUN_NUMBER k8s-best-practices-guide.pdf

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
